services:
  slythera:
    build: .
    image: mohamedkhalilzrelly/slythera:latest
    container_name: slythera
    volumes:
      - ./model:/app/model
      - ./assets:/app/assets
    working_dir: /app
    environment:
      - DISPLAY=host.docker.internal:0
      - TF_ENABLE_ONEDNN_OPTS=0
    stdin_open: true
    tty: true
